language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script: 
  - python manager.py test
  - coverage run --source=shanbay manager.py test

after_success:
  coveralls
